//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchTable
    {
        public int MatchId { get; set; }
        public string MatchNo { get; set; }
        public System.DateTime MatchDay { get; set; }
        public string MatchDetails { get; set; }
    }
}
