//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QPL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToTeamMapping
    {
        public int UserToTeamMappingId { get; set; }
        public int UserId { get; set; }
        public int TeamId { get; set; }
        public int BidPoints { get; set; }
        public bool IsOwner { get; set; }
    }
}
