//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLEntities : DbContext
    {
        public QLEntities()
            : base("name=QLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_QL_Match_Prediction> T_QL_Match_Prediction { get; set; }
        public virtual DbSet<T_QL_PredictionUsers> T_QL_PredictionUsers { get; set; }
    
        public virtual int SP_QL_AddMatchPrediction(string nT_ID, string stage1WinnerTeam, string stage2WinnerTeam, string stage3WinnerTeam, string winnerTeam)
        {
            var nT_IDParameter = nT_ID != null ?
                new ObjectParameter("NT_ID", nT_ID) :
                new ObjectParameter("NT_ID", typeof(string));
    
            var stage1WinnerTeamParameter = stage1WinnerTeam != null ?
                new ObjectParameter("Stage1WinnerTeam", stage1WinnerTeam) :
                new ObjectParameter("Stage1WinnerTeam", typeof(string));
    
            var stage2WinnerTeamParameter = stage2WinnerTeam != null ?
                new ObjectParameter("Stage2WinnerTeam", stage2WinnerTeam) :
                new ObjectParameter("Stage2WinnerTeam", typeof(string));
    
            var stage3WinnerTeamParameter = stage3WinnerTeam != null ?
                new ObjectParameter("Stage3WinnerTeam", stage3WinnerTeam) :
                new ObjectParameter("Stage3WinnerTeam", typeof(string));
    
            var winnerTeamParameter = winnerTeam != null ?
                new ObjectParameter("WinnerTeam", winnerTeam) :
                new ObjectParameter("WinnerTeam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_QL_AddMatchPrediction", nT_IDParameter, stage1WinnerTeamParameter, stage2WinnerTeamParameter, stage3WinnerTeamParameter, winnerTeamParameter);
        }
    
        public virtual ObjectResult<SP_QL_GetCurrentPredictionMatchDetails_Result> SP_QL_GetCurrentPredictionMatchDetails()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_QL_GetCurrentPredictionMatchDetails_Result>("SP_QL_GetCurrentPredictionMatchDetails");
        }
    
        public virtual ObjectResult<Nullable<int>> SP_QL_PredictionUserLogin(string nT_ID, string password)
        {
            var nT_IDParameter = nT_ID != null ?
                new ObjectParameter("NT_ID", nT_ID) :
                new ObjectParameter("NT_ID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_QL_PredictionUserLogin", nT_IDParameter, passwordParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_QL_PredictionUserSignUp(string nT_ID, string department, string password)
        {
            var nT_IDParameter = nT_ID != null ?
                new ObjectParameter("NT_ID", nT_ID) :
                new ObjectParameter("NT_ID", typeof(string));
    
            var departmentParameter = department != null ?
                new ObjectParameter("Department", department) :
                new ObjectParameter("Department", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_QL_PredictionUserSignUp", nT_IDParameter, departmentParameter, passwordParameter);
        }
    }
}
